name: build and upload

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
          cache: true
      - run: curl -sSL https://ftp.lunarware.tech/randomrefs/refs.tar.gz | tar xvzf -
      - run: mv refs/ NineFourteenTeleport/refs
      - run: dotnet restore
      - run: dotnet build 
      - uses: actions/upload-artifact@v4.5.0
        with:
          path: NineFourteenTeleport/bin/Debug/net48/NineFourteenTeleport.dll
